import React from 'react';
import { Chart } from "react-google-charts";

const columns = [
    { type: "string", label: "Task ID" },
    { type: "string", label: "Task Name" },
    { type: "string", label: "Resource" },
    { type: "date", label: "Start Date" },
    { type: "date", label: "End Date" },
    { type: "number", label: "Duration" },
    { type: "number", label: "Percent Complete" },
    { type: "string", label: "Dependencies" },
];

const rows = [
    [
        "a",
        "Mise en sécurité plomberie du chantier",
        "a",
        new Date(2023, 5, 18),
        new Date(2023, 5, 19),
        null,
        100,
        null,
    ],
    [
        "b",
        "Pose du carrelage dans toutes les pièces de vie et faíence de la douche",
        "b",
        new Date(2023, 7, 17),
        new Date(2023, 7, 20),
        null,
        100,
        null,
    ],
    [
        "c",
        "Installation de la cuisine",
        "c",
        new Date(2023, 7, 17),
        new Date(2023, 7, 18),
        null,
        100,
        null,
    ],
    [
        "d",
        "Démolition de tout l'intérieur de l'habitation (cloisons, plafonds, dalle béton) et évacuation des déchets",
        "d",
        new Date(2023, 5, 18),
        new Date(2023, 5, 23),
        null,
        100,
        null,
    ],
    [
        "e",
        "Mise en sécurité électrique du chantier",
        "e",
        new Date(2023, 5, 18),
        new Date(2023, 5, 19),
        null,
        100,
        null,
    ],
    [
        "f",
        "Mise en peinture de l'intégralité du logement",
        "f",
        new Date(2023, 7, 20),
        new Date(2023, 7, 23),
        null,
        100,
        null,
    ],
    [
        "g",
        "Installation d'un dressing",
        "g",
        new Date(2023, 7, 17),
        new Date(2023, 7, 18),
        null,
        100,
        null,
    ],
    [
        "h",
        "Réfection complète de la charpente",
        "h",
        new Date(2023, 5, 23),
        new Date(2023, 5, 26),
        null,
        100,
        null,
    ],
    [
        "i",
        "Pose des sols de la chambre",
        "i",
        new Date(2023, 7, 23),
        new Date(2023, 7, 24),
        null,
        100,
        null,
    ],
    [
        "j",
        "Pose des sols de la chambre",
        "j",
        new Date(2023, 7, 17),
        new Date(2023, 7, 18),
        null,
        100,
        null,
    ],
    [
        "k",
        "Réfection complète de la couverture",
        "k",
        new Date(2023, 5, 26),
        new Date(2023, 5, 31),
        null,
        100,
        null,
    ],
    [
        "l",
        "Installation des équipements de salle de bains (meuble vasque, chauffe-eau)",
        "l",
        new Date(2023, 7, 17),
        new Date(2023, 7, 18),
        null,
        100,
        null,
    ],
    [
        "m",
        "Installation des zingueries",
        "m",
        new Date(2023, 5, 31),
        new Date(2023, 6, 2),
        null,
        100,
        null,
    ],
    [
        "n",
        "Passage du réseau d'évacuation en sous-dallage et raccordement au tout à l'égout",
        "n",
        new Date(2023, 6, 2),
        new Date(2023, 6, 4),
        null,
        100,
        null,
    ],
    [
        "o",
        "Préparation et coulage de la dalle",
        "o",
        new Date(2023, 6, 4),
        new Date(2023, 6, 7),
        null,
        100,
        null,
    ],
    [
        "p",
        "Séchage de la dalle",
        "p",
        new Date(2023, 6, 7),
        new Date(2023, 6, 28),
        null,
        100,
        null,
    ],
    [
        "q",
        "Remplacement de toutes les huisseries",
        "q",
        new Date(2023, 6, 28),
        new Date(2023, 6, 29),
        null,
        100,
        null,
    ],
    [
        "r",
        "Réfection compléte de la façade et mise en peinture",
        "r",
        new Date(2023, 6, 29),
        new Date(2023, 7, 2),
        null,
        100,
        null,
    ],
    [
        "s",
        "Implantation des cloisons, raillage, isolation",
        "s",
        new Date(2023, 7, 2),
        new Date(2023, 7, 5),
        null,
        100,
        null,
    ],
    [
        "t",
        "Cablage total du logement",
        "t",
        new Date(2023, 7, 5),
        new Date(2023, 7, 7),
        null,
        100,
        null,
    ],
    [
        "u",
        "Installation de tous les réseaux d'alimentation en eau",
        "u",
        new Date(2023, 7, 7),
        new Date(2023, 7, 8),
        null,
        100,
        null,
    ],
    [
        "v",
        "Plaquage de l'intégralité du logement",
        "v",
        new Date(2023, 7, 8),
        new Date(2023, 7, 11),
        null,
        100,
        null,
    ],
    [
        "w",
        "Réalisation des bandes de placo-plâtre",
        "w",
        new Date(2023, 7, 11),
        new Date(2023, 7, 14),
        null,
        100,
        null,
    ],
    [
        "x",
        "Installation de tous les éléments sanitaires (douche, toilettes..)",
        "x",
        new Date(2023, 7, 14),
        new Date(2023, 7, 15),
        null,
        100,
        null,
    ],
    [
        "y",
        "Installation de tous les appareillages et équipements électriques",
        "y",
        new Date(2023, 7, 15),
        new Date(2023, 7, 17),
        null,
        100,
        null,
    ],
    [
        "z",
        "Passage du contrôleur consuel",
        "z",
        new Date(2023, 7, 17),
        new Date(2023, 7, 17),
        null,
        100,
        null,
    ],
];

export const data = [columns, ...rows];

export const options = {
    height: 850,
    gantt: {
        trackHeight: 30,
    },
};


const GanttChart = () => {

    return (
        <div>
            <Chart
                chartType="Gantt"
                width="100%"
                height="50%"
                data={data}
                options={options}
            />
        </div>
    );
};

export default GanttChart;